### ISSUE TITLE
Add whitespace to list of invalid characters for minecraft username in application

### ISSUE THREAD

**Issue by Selida95** [mattboy9921/MauveList#12]

**Comment by mattboy9921** [comment]
If you look here:
https://github.com/mattboy9921/MauveList/blob/eb61fabc86989a594264dec9d8fe78a488b035e9/src/main/java/net/mattlabs/mauvelist/util/PlayerUtils.java#L55
`username.matches("\\w+")` will only match alphanumeric characters and the underscore. So spaces will cause this to be false and invalidate the check.
This is code from the upcoming release so it should be fixed once that comes out.
